version: "3.9"

services:
  db:
    image: postgres:15
    container_name: observability_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vishal
      POSTGRES_DB: logs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: observability_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./scripts:/app/scripts 
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
